repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff

  - repo: local
    hooks:
      - id: mypy-local
        name: mypy (venv, follow-untyped-imports)
        entry: python -m mypy . --follow-untyped-imports
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
      - id: pytest-all
        name: Run all tests
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
