repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1  # or latest
    hooks:
      - id: gitleaks
        name: Check for sensitive data with gitleaks

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff

  - repo: local
    hooks:
      - id: mypy-local
        name: mypy (venv, follow-untyped-imports)
        entry: python -m mypy . --follow-untyped-imports
        language: system
        pass_filenames: false
        always_run: true
      - id: pytest-fast
        name: Run fast tests
        entry: pytest -m "not integration"
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
      - id: pytest-slow
        name: Run slow tests
        entry: pytest -m "integration"
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
